# Generated by Django 4.2.7 on 2023-12-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='config',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
