# Generated by Django 4.2.7 on 2023-12-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0003_alter_device_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='config',
            field=models.CharField(choices=[('simple_queue', 'Simple Queue'), ('queue_three', 'Queue Three'), ('HTB', 'HTB')], default='default', max_length=255),
        ),
    ]
